package com.android.compose.ui.theme

import androidx.compose.ui.graphics.Color

// Generate them via theme builder
// https://material-foundation.github.io/material-theme-builder/#/custom

val composeLightPrimary = Color(0xFF825500)
val composeLightOnPrimary = Color(0xFFFFFFFF)
val composeLightPrimaryContainer = Color(0xFFFFDDAE)
val composeLightOnPrimaryContainer = Color(0xFF2A1800)
val composeLightSecondary = Color(0xFF6F5B40)
val composeLightOnSecondary = Color(0xFFFFFFFF)
val composeLightSecondaryContainer = Color(0xFFFADEBC)
val composeLightOnSecondaryContainer = Color(0xFF271904)
val composeLightTertiary = Color(0xFF516440)
val composeLightOnTertiary = Color(0xFFFFFFFF)
val composeLightTertiaryContainer = Color(0xFFD3EABC)
val composeLightOnTertiaryContainer = Color(0xFF102004)
val composeLightError = Color(0xFFBA1B1B)
val composeLightErrorContainer = Color(0xFFFFDAD4)
val composeLightOnError = Color(0xFFFFFFFF)
val composeLightOnErrorContainer = Color(0xFF410001)
val composeLightBackground = Color(0xFFFCFCFC)
val composeLightOnBackground = Color(0xFF1F1B16)
val composeLightSurface = Color(0xFFFCFCFC)
val composeLightOnSurface = Color(0xFF1F1B16)
val composeLightSurfaceVariant = Color(0xFFF0E0CF)
val composeLightOnSurfaceVariant = Color(0xFF4F4539)
val composeLightOutline = Color(0xFF817567)
val composeLightInverseOnSurface = Color(0xFFF9EFE6)
val composeLightInverseSurface = Color(0xFF34302A)
val composeLightPrimaryInverse = Color(0xFFFFB945)

val composeDarkPrimary = Color(0xFFFFB945)
val composeDarkOnPrimary = Color(0xFF452B00)
val composeDarkPrimaryContainer = Color(0xFF624000)
val composeDarkOnPrimaryContainer = Color(0xFFFFDDAE)
val composeDarkSecondary = Color(0xFFDDC3A2)
val composeDarkOnSecondary = Color(0xFF3E2E16)
val composeDarkSecondaryContainer = Color(0xFF56442B)
val composeDarkOnSecondaryContainer = Color(0xFFFADEBC)
val composeDarkTertiary = Color(0xFFB8CEA2)
val composeDarkOnTertiary = Color(0xFF243516)
val composeDarkTertiaryContainer = Color(0xFF3A4C2B)
val composeDarkOnTertiaryContainer = Color(0xFFD3EABC)
val composeDarkError = Color(0xFFFFB4A9)
val composeDarkErrorContainer = Color(0xFF930006)
val composeDarkOnError = Color(0xFF680003)
val composeDarkOnErrorContainer = Color(0xFFFFDAD4)
val composeDarkBackground = Color(0xFF1F1B16)
val composeDarkOnBackground = Color(0xFFEAE1D9)
val composeDarkSurface = Color(0xFF1F1B16)
val composeDarkOnSurface = Color(0xFFEAE1D9)
val composeDarkSurfaceVariant = Color(0xFF4F4539)
val composeDarkOnSurfaceVariant = Color(0xFFD3C4B4)
val composeDarkOutline = Color(0xFF9C8F80)
val composeDarkInverseOnSurface = Color(0xFF32281A)
val composeDarkInverseSurface = Color(0xFFEAE1D9)
val composeDarkPrimaryInverse = Color(0xFF624000)
